# Generated by Django 5.1.5 on 2025-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_sensordata_counter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
