# Generated by Django 5.1.5 on 2025-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_sensordata_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
